const coinNameKR = {
  bithumb: {
    BTC: '비트코인',
    ETH: '이더리움',
    XRP: '리플',
    EOS: '이오스',
    LTC: '라이트코인',
    BCH: '비트코인캐시',
    ZIL: '질리카',
    LINK: '체인링크',
    BSV: '비트코인에스브이',
    THETA: '쎄타토큰',
    XLM: '스텔라루멘',
    YFI: '연파이낸스',
    ADA: '에이다',
    TRX: '트론',
    VET: '비체인',
    XEM: '넴',
    ETC: '이더리움 클래식',
    AWO: '에이아이워크',
    ZRX: '제로엑스',
    CVT: '사이버베인',
    QTUM: '퀀텀',
    ZEC: '제트캐시',
    OMG: '오미세고',
    SXP: '스와이프',
    TMTG: '더마이다스터치골드',
    BTG: '비트코인 골드',
    BASIC: '베이직',
    ANKR: '앵커',
    ALGO: '알고랜드',
    ONG: '온톨로지가스',
    SUN: '썬',
    DASH: '대시',
    BCD: '비트코인 다이아몬드',
    BORA: '보라',
    POLA: '폴라리스 쉐어',
    WAVES: '웨이브',
    KNC: '카이버 네트워크',
    FIT: '300피트 네트워크',
    LUNA: '루나',
    QKC: '쿼크체인',
    CENNZ: '센트럴리티',
    REP: '어거',
    FCT: '피르마체인',
    ATOM: '코스모스',
    BCHA: '비트코인 캐시 에이비씨',
    MTL: '메탈',
    ELF: '엘프',
    STRAX: '스트라티스',
    HDAC: '에이치닥',
    ICX: '아이콘',
    AE: '애터니티',
    META: '메타디움',
    XTZ: '테조스',
    IPX: '타키온프로토콜',
    TEMCO: '템코',
    OBSR: '옵저버',
    SAND: '샌드박스',
    DVP: '디브이피',
    GOM2: '고머니2',
    ENJ: '엔진코인',
    CON: '코넌',
    ARPA: '알파체인',
    EVZ: '이브이지',
    UNI: '유니스왑',
    DAC: '다빈치',
    WET: '위쇼토큰',
    JST: '저스트',
    BAT: '베이직어텐션토큰',
    XSR: '젠서',
    WTC: '월튼체인',
    ADP: '어댑터 토큰',
    UMA: '우마',
    SNT: '스테이터스네트워크토큰',
    GLM: '골렘',
    ONT: '온톨로지',
    LOOM: '룸네트워크',
    EGG: '네스트리',
    STEEM: '스팀',
    TRUE: '트루체인',
    POWR: '파워렛저',
    SOC: '소다코인',
    WAXP: '왁스',
    VSYS: '브이시스템즈',
    MBL: '무비블록',
    APM: '에이피엠 코인',
    XPR: '프로톤',
    ORC: '오르빗 체인',
    LRC: '루프링',
    LAMB: '람다',
    PIVX: '피벡스',
    NPXS: '펀디엑스',
    MXC: '머신익스체인지코인',
    AMO: '아모코인',
    MLK: '밀크',
    IOST: '이오스트',
    QTCON: '퀀텀',
    BTT: '비트토렌트',
    ORBS: '오브스',
    CRO: '크립토닷컴체인',
    SRM: '세럼',
    QBZ: '퀸비',
    COS: '콘텐토스',
    WEMIX: '위믹스',
    CHR: '크로미아',
    APIX: '아픽스',
    FNB: '에프앤비프로토콜',
    BOA: '보아',
    MCI: '엠씨아이',
    RINGX: '링엑스',
    CTXC: '코르텍스',
    FLETA: '플레타',
    PCM: '프레시움',
    LBA: '크레드',
    MIX: '믹스마블',
    HYC: '하이콘',
    GXC: '지엑스체인',
    BZNT: '베잔트',
    OGO: '오리고',
    VALOR: '밸러토큰',
    HIVE: '하이브',
    AION: '아이온',
    WICC: '웨이키체인',
    RNT: '원루트 네트워크',
    WOM: '왐토큰',
    ANW: '앵커뉴럴월드',
    TRV: '트러스트버스',
    FX: '펑션엑스',
    DAD: '다드',
    DOT: '폴카닷',
    EL: '엘리시아',
    AOA: '오로라',
    EM: '이마이너'
  },
};

export { coinNameKR };