const coinNameKR = {
  bithumb: {
    BTC: '비트코인',
    ETH: '이더리움',
    XRP: '리플',
    EOS: '이오스',
    LTC: '라이트코인',
    BCH: '비트코인캐시',
    ZIL: '질리카',
    LINK: '체인링크',
    BSV: '비트코인에스브이',
    THETA: '쎄타토큰',
    XLM: '스텔라루멘',
    YFI: '연파이낸스',
    ADA: '에이다',
    TRX: '트론',
    VET: '비체인',
    XEM: '넴',
    ETC: '이더리움 클래식',
    AWO: '에이아이워크',
    ZRX: '제로엑스',
    CVT: '사이버베인',
    QTUM: '퀀텀',
    ZEC: '제트캐시',
    OMG: '오미세고',
    SXP: '스와이프',
    TMTG: '더마이다스터치골드',
    BTG: '비트코인 골드',
    BASIC: '베이직',
    ANKR: '앵커',
    ALGO: '알고랜드',
    ONG: '온톨로지가스',
    SUN: '썬',
    DASH: '대시',
    BCD: '비트코인 다이아몬드',
    BORA: '보라',
    POLA: '폴라리스 쉐어',
    WAVES: '웨이브',
    KNC: '카이버 네트워크',
    FIT: '300피트 네트워크',
    LUNA: '루나',
    QKC: '쿼크체인',
    CENNZ: '센트럴리티',
    REP: '어거',
    FCT: '피르마체인',
    ATOM: '코스모스',
    BCHA: '비트코인 캐시 에이비씨',
    MTL: '메탈',
    ELF: '엘프',
    STRAX: '스트라티스',
    HDAC: '에이치닥',
    ICX: '아이콘',
    AE: '애터니티',
    META: '메타디움',
    XTZ: '테조스',
    IPX: '타키온프로토콜',
    TEMCO: '템코',
    OBSR: '옵저버',
    SAND: '샌드박스',
    DVP: '디브이피',
    GOM2: '고머니2',
    ENJ: '엔진코인',
    CON: '코넌',
    ARPA: '알파체인',
    EVZ: '이브이지',
    UNI: '유니스왑',
    DAC: '다빈치',
    WET: '위쇼토큰',
    JST: '저스트',
    BAT: '베이직어텐션토큰',
    XSR: '젠서',
    WTC: '월튼체인',
    ADP: '어댑터 토큰',
    UMA: '우마',
    SNT: '스테이터스네트워크토큰',
    GLM: '골렘',
    ONT: '온톨로지',
    LOOM: '룸네트워크',
    EGG: '네스트리',
    STEEM: '스팀',
    TRUE: '트루체인',
    POWR: '파워렛저',
    SOC: '소다코인',
    WAXP: '왁스',
    VSYS: '브이시스템즈',
    MBL: '무비블록',
    APM: '에이피엠 코인',
    XPR: '프로톤',
    ORC: '오르빗 체인',
    LRC: '루프링',
    LAMB: '람다',
    PIVX: '피벡스',
    NPXS: '펀디엑스',
    MXC: '머신익스체인지코인',
    AMO: '아모코인',
    MLK: '밀크',
    IOST: '이오스트',
    QTCON: '퀴즈톡',
    BTT: '비트토렌트',
    ORBS: '오브스',
    CRO: '크립토닷컴체인',
    SRM: '세럼',
    QBZ: '퀸비',
    COS: '콘텐토스',
    WEMIX: '위믹스',
    CHR: '크로미아',
    APIX: '아픽스',
    FNB: '에프앤비프로토콜',
    BOA: '보아',
    MCI: '엠씨아이',
    RINGX: '링엑스',
    CTXC: '코르텍스',
    FLETA: '플레타',
    PCM: '프레시움',
    LBA: '크레드',
    MIX: '믹스마블',
    HYC: '하이콘',
    GXC: '지엑스체인',
    BZNT: '베잔트',
    OGO: '오리고',
    VALOR: '밸러토큰',
    HIVE: '하이브',
    AION: '아이온',
    WICC: '웨이키체인',
    RNT: '원루트 네트워크',
    WOM: '왐토큰',
    ANW: '앵커뉴럴월드',
    TRV: '트러스트버스',
    FX: '펑션엑스',
    DAD: '다드',
    DOT: '폴카닷',
    EL: '엘리시아',
    AOA: '오로라',
    EM: '이마이너',
    MIR: '미러 프로토콜',
    DVC: '드래곤베인',
    WOZX: '이포스'
  },
};

const coinNameV2 = [
  { BTC: '비트코인', BT: true, BN: 'USDT' }, //i = 0
  { ETH: '이더리움', BT: true, BN: 'USDT' }, //i = 1
  { LTC: '라이트코인', BT: true, BN: 'USDT' },
  { ETC: '이더리움 클래식', BT: true, BN: 'USDT' },
  { XRP: '리플', BT: true, BN: 'USDT' },
  { BCH: '비트코인캐시', BT: true, BN: 'USDT' },
  { QTUM: '퀀텀', BT: true, BN: 'USDT' },
  { BTG: '비트코인 골드', BT: true, BN: 'BTC' },
  { EOS: '이오스', BT: true, BN: 'USDT' },
  { ICX: '아이콘', BT: true, BN: 'USDT' },
  { TRX: '트론', BT: true, BN: 'USDT' }, //i = 12
  { ELF: '엘프', BT: true, BN: 'ETH' },
  { OMG: '오미세고', BT: true, BN: 'USDT' },
  { KNC: '카이버 네트워크', BT: true, BN: 'USDT' },
  { GLM: '골렘', BT: true, BN: 'ETH' },
  { ZIL: '질리카', BT: true, BN: 'USDT' },
  { WAXP: '왁스', BT: true, BN: false },
  { POWR: '파워렛저', BT: true, BN: 'ETH' },
  { LRC: '루프링', BT: true, BN: 'USDT' },
  { STEEM: '스팀', BT: true, BN: 'ETH' },
  { STRAX: '스트라티스', BT: true, BN: 'USDT' },
  { AE: '애터니티', BT: true, BN: false },
  { ZRX: '제로엑스', BT: true, BN: 'USDT' },
  { REP: '어거', BT: true, BN: 'USDT' },
  { XEM: '넴', BT: true, BN: 'USDT' },
  { SNT: '스테이터스네트워크토큰', BT: true, BN: 'ETH' },
  { ADA: '에이다', BT: true, BN: 'USDT' },
  { CTXC: '코르텍스', BT: true, BN: 'USDT' },
  { BAT: '베이직어텐션토큰', BT: true, BN: 'USDT' },
  { WTC: '월튼체인', BT: true, BN: 'USDT' },
  { THETA: '쎄타토큰', BT: true, BN: 'USDT' },
  { LOOM: '룸네트워크', BT: true, BN: 'ETH' },
  { WAVES: '웨이브', BT: true, BN: 'USDT' },
  { TRUE: '트루체인', BT: true, BN: false },
  { LINK: '체인링크', BT: true, BN: 'USDT' },
  { RNT: '원루트 네트워크', BT: true, BN: false },
  { ENJ: '엔진코인', BT: true, BN: 'USDT' },
  { VET: '비체인', BT: true, BN: 'USDT' },
  { MTL: '메탈', BT: true, BN: 'USDT' },
  { IOST: '이오스트', BT: true, BN: 'USDT' },
  { TMTG: '더마이다스터치골드', BT: true, BN: false },
  { QKC: '쿼크체인', BT: true, BN: 'BTC' },
  { HDAC: '에이치닥', BT: true, BN: false },
  { NPXS: '펀디엑스', BT: true, BN: 'USDT' },
  { WET: '위쇼토큰', BT: true, BN: false },
  { AMO: '아모코인', BT: true, BN: false },
  { BSV: '비트코인에스브이', BT: true, BN: false },
  { DAC: '다빈치', BT: true, BN: false },
  { ORBS: '오브스', BT: true, BN: false },
  { VALOR: '밸러토큰', BT: true, BN: false },
  { CON: '코넌', BT: true, BN: false },
  { ANKR: '앵커', BT: true, BN: 'USDT' },
  { MIX: '믹스마블', BT: true, BN: false },
  { LAMB: '람다', BT: true, BN: false },
  { CRO: '크립토닷컴체인', BT: true, BN: false },
  { FX: '펑션엑스', BT: true, BN: false },
  { CHR: '크로미아', BT: true, BN: 'USDT' },
  { MBL: '무비블록', BT: true, BN: 'USDT' },
  { MXC: '머신익스체인지코인', BT: true, BN: false },
  { DVP: '디브이피', BT: true, BN: false },
  { FCT: '피르마체인', BT: true, BN: false },
  { FNB: '에프앤비프로토콜', BT: true, BN: false },
  { TRV: '트러스트버스', BT: true, BN: false },
  { PCM: '프레시움', BT: true, BN: false },
  { DAD: '다드', BT: true, BN: false },
  { AOA: '오로라', BT: true, BN: false },
  { XSR: '젠서', BT: true, BN: false },
  { WOM: '왐토큰', BT: true, BN: false },
  { SOC: '소다코인', BT: true, BN: false },
  { EM: '이마이너', BT: true, BN: false },
  { QBZ: '퀸비', BT: true, BN: false },
  { BOA: '보아', BT: true, BN: false },
  { FLETA: '플레타', BT: true, BN: false },
  { SXP: '스와이프', BT: true, BN: 'USDT' },
  { COS: '콘텐토스', BT: true, BN: 'USDT' },
  { APIX: '아픽스', BT: true, BN: false },
  { EL: '엘리시아', BT: true, BN: false },
  { BASIC: '베이직', BT: true, BN: false },
  { HIVE: '하이브', BT: true, BN: 'USDT' },
  { XPR: '프로톤', BT: true, BN: false },
  { FIT: '300피트 네트워크', BT: true, BN: false },
  { EGG: '네스트리', BT: true, BN: false },
  { BORA: '보라', BT: true, BN: false },
  { ARPA: '알파체인', BT: true, BN: 'USDT' },
  { APM: '에이피엠 코인', BT: true, BN: false },
  { AERGO: '아르고', BT: true, BN: 'BUSD' },
  { ANW: '앵커뉴럴월드', BT: true, BN: false },
  { CENNZ: '센트럴리티', BT: true, BN: false },
  { EVZ: '이브이지', BT: true, BN: false },
  { MCI: '엠씨아이', BT: true, BN: false },
  { SRM: '세럼', BT: true, BN: 'BIDR' },
  { QTCON: '퀀텀', BT: true, BN: false },
  { UNI: '유니스왑', BT: true, BN: 'USDT' },
  { YFI: '연파이낸스', BT: true, BN: 'USDT' },
  { UMA: '우마', BT: true, BN: 'USDT' },
  { AAVE: '에이브', BT: true, BN: 'USDT' },
  { COMP: '컴파운드', BT: true, BN: 'USDT' },
  { SAND: '샌드박스', BT: true, BN: 'USDT' },
  { CVT: '사이버베인', BT: true, BN: false },
  { GOM2: '고머니2', BT: true, BN: false },
  { RINGX: '링엑스', BT: true, BN: false },
  { BEL: '벨라프로토콜', BT: true, BN: 'USDT' },
  { DVC: '드래곤베인', BT: true, BN: false },
  { OBSR: '옵저버', BT: true, BN: false },
  { ORC: '오르빗 체인', BT: true, BN: false },
  { POLA: '폴라리스 쉐어', BT: true, BN: false },
  { AWO: '에이아이워크', BT: true, BN: 'USDT' },
  { ADP: '어댑터 토큰', BT: true, BN: false },
  { DVI: '디비전', BT: true, BN: false },
  { MIR: '미러 프로토콜', BT: true, BN: false },
  { MVC: '마일벌스', BT: true, BN: false },
  { WOZX: '이포스', BT: true, BN: false },
  { ANV: '애니버스', BT: true, BN: false },
  { GRT: '더그래프', BT: true, BN: 'USDT' },
  { MM: '밀리미터토큰', BT: true, BN: false },
  { BIOT: '바이오패스포트', BT: true, BN: false },
  { XNO: '제노토큰', BT: true, BN: false },
  { SNX: '신세틱스', BT: true, BN: 'USDT' },
  { OXT: '오키드', BT: true, BN: 'USDT' },
  { LINA: '리니어파이낸스', BT: true, BN: 'USDT' },
  { MKR: '메이커', BT: true, BN: 'USDT' },
  { SUSHI: '스시스왑', BT: true, BN: 'USDT' },
  { PUNDIX: '펀디엑스', BT: true, BN: 'USDT' },
  { LF: '링크플로우', BT: true, BN: false },
  { ALICE: '마이네이버앨이스', BT: true, BN: 'USDT' },
  { BCD: '비트코인 다이아몬드', BT: true, BN: 'BTC' },
  { XLM: '스텔라루멘', BT: true, BN: 'USDT' },
  { GXC: '지엑스체인', BT: true, BN: false },
  { BTT: '비트토렌트', BT: true, BN: 'TRX' },
  { VSYS: '브이시스템즈', BT: true, BN: false },
  { IPX: '타키온프로토콜', BT: true, BN: false },
  { WICC: '웨이키체인', BT: true, BN: false },
  { ONT: '온톨로지', BT: true, BN: 'USDT' },
  { LUNA: '루나', BT: true, BN: 'USDT' },
  { AION: '아이온', BT: true, BN: 'USDT' },
  { META: '메타디움', BT: true, BN: false },
  { ONG: '온톨로지가스', BT: true, BN: 'USDT' },
  { ALGO: '알고랜드', BT: true, BN: 'USDT' },
  { JST: '저스트', BT: true, BN: 'USDT' },
  { XTZ: '테조스', BT: true, BN: 'USDT' },
  { MLK: '밀크', BT: true, BN: false },
  { WEMIX: '위믹스', BT: true, BN: false },
  { DOT: '폴카닷', BT: true, BN: 'BIDR' },
  { SUN: '썬', BT: true, BN: 'USDT' },
  { ATOM: '코스모스', BT: true, BN: 'USDT' },
  { SSX: '썸씽', BT: true, BN: false },
  { BCHA: '비트코인 캐시 에이비씨', BT: true, BN: 'BUSD' },
  { TEMCO: '템코', BT: true, BN: false },
  { BURGER: '버거스왑', BT: true, BN: 'BNB' },
];
//ETH BUSD BIDR TRX BTC
export { coinNameKR, coinNameV2 };